-- Copy and paste this script into the Supabase SQL Editor and click RUN.

-- 1. Create Users Table (Stores profile info)
create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  email text unique not null,
  name text,
  role text, -- 'Manager', 'Doctor', 'Staff'
  dept text,
  avatar text
);

-- 2. Insert Default Users (Matching your existing data)
insert into public.app_users (email, name, role, dept, avatar) values
('doctor@sreedhari.com', 'Dr. A. Nair', 'Doctor', 'Consultation', 'DR'),
('manager@sreedhari.com', 'Sreejith Manager', 'Manager', 'Administration', 'SR'),
('staff@sreedhari.com', 'General Staff', 'Staff', 'Operations', 'GS'),
('sreejithsdev@gmail.com', 'Sreejith (Admin)', 'Manager', 'Administration', 'SA')
on conflict (email) do nothing;

-- 3. Create Schedules/Tasks Table
create table if not exists public.schedules (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    type text,
    staff text,     -- e.g. 'Santamma'
    patient text,
    time text,      -- e.g. '08:00'
    task text,
    status text default 'Pending', -- 'Pending', 'Accepted', 'Completed'
    accepted_by text,
    accepted_at text,
    completed_by text,
    completed_at text,
    completion_note text,
    comments jsonb default '[]'::jsonb
);

-- 4. Create Notifications Table
create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    user_id bigint, -- Links to app_users.id
    text text,
    read boolean default false,
    time_label text -- e.g. 'Just now'
);

-- 5. Enable Realtime (This allows instant updates on all devices)
alter publication supabase_realtime add table public.schedules;
alter publication supabase_realtime add table public.notifications;

-- 6. Grant Access (Simple Public Access for this Demo Level)
-- Note: For production, you would set up Row Level Security (RLS) policies.
alter table public.app_users enable row level security;
create policy "Public Access Users" on public.app_users for all using (true);

alter table public.schedules enable row level security;
create policy "Public Access Schedules" on public.schedules for all using (true);

alter table public.notifications enable row level security;
create policy "Public Access Notifications" on public.notifications for all using (true);
