import { store } from '../store.js';

// Global handler for adding patient records
window.handleAddRecord = (e, type, patientId) => {
    e.preventDefault();
    const form = e.target;

    if (type === 'history') {
        const typeVal = form.elements['record-type'].value;
        const notes = form.elements['record-notes'].value;
        store.updatePatientHistory(patientId, { type: typeVal, notes: notes, by: 'Current User' });
    } else if (type === 'treatment') {
        const name = form.elements['treatment-name'].value;
        const duration = form.elements['treatment-duration'].value;
        store.addPatientTreatment(patientId, { name, duration, status: 'Scheduled', notes: '' });
    } else if (type === 'medication') {
        const name = form.elements['med-name'].value;
        const dosage = form.elements['med-dosage'].value;
        store.addPatientMedication(patientId, { name, dosage, status: 'Active' });
    }

    // Refresh view
    renderPatientDetails(patientId);
    form.reset();
};

function renderPatientDetails(id) {
    const patient = store.getPatient(id);
    if (!patient) return alert('Patient not found');

    const currentUser = store.getCurrentUser();
    const isStaff = currentUser && currentUser.role === 'Staff';

    // Staff cannot see the History Card
    const historySection = isStaff ?
        `<div class="card" style="display: flex; flex-direction: column; align-items: center; justify-content: center; height: 100%; opacity: 0.7;">
            <i data-lucide="lock" style="width: 48px; height: 48px; color: var(--text-muted); margin-bottom: 1rem;"></i>
            <h3 style="color: var(--text-muted);">Restricted Access</h3>
            <p style="color: var(--text-muted); font-size: 0.9rem;">Medical history is confidential.</p>
        </div>`
        :
        `<div class="card">
            <h3 style="margin-bottom: 1.5rem; font-weight: 600;">Medical History & Notes</h3>
            
            <!-- Add Note Form -->
            <form onsubmit="handleAddRecord(event, 'history', ${id})" style="margin-bottom: 2rem; padding-bottom: 2rem; border-bottom: 1px solid var(--border-color);">
                <div style="display: flex; gap: 1rem; margin-bottom: 1rem;">
                    <select name="record-type" style="padding: 0.5rem; border: 1px solid var(--border-color); border-radius: var(--radius-md); background: white;">
                        <option>Consultation</option>
                        <option>Daily Observation</option>
                        <option>Lab Result</option>
                    </select>
                    <input name="record-notes" type="text" placeholder="Enter clinical notes..." required style="flex: 1; padding: 0.5rem; border: 1px solid var(--border-color); border-radius: var(--radius-md);">
                    <button type="submit" class="btn btn-primary" style="padding: 0.5rem 1rem;">Add Note</button>
                </div>
            </form>

            <div class="timeline">
                ${patient.history.length > 0 ? patient.history.map(h => `
                    <div class="timeline-item" style="padding: 1rem; border-left: 2px solid var(--border-color); margin-left: 1rem; position: relative;">
                        <div style="position: absolute; left: -6px; top: 1.5rem; width: 10px; height: 10px; background: var(--primary); border-radius: 50%;"></div>
                        <div style="font-size: 0.8rem; color: var(--text-muted); margin-bottom: 0.25rem;">${h.date} • ${h.type} • ${h.by}</div>
                        <p>${h.notes}</p>
                    </div>
                `).join('') : '<p style="color: var(--text-muted); text-align: center;">No history recorded yet.</p>'}
            </div>
        </div>`;

    // Helper to generate text from actual records
    const getAutoGeneratedSummary = () => {
        let tText = '';
        if (patient.treatments && patient.treatments.length > 0) {
            tText = "Treatment History:\n" + patient.treatments.map(t => `- ${t.name} (${t.duration})`).join('\n');
        } else {
            tText = "No specific treatments recorded.";
        }

        let mText = '';
        if (patient.medications && patient.medications.length > 0) {
            mText = "Prescribed Medications:\n" + patient.medications.map(m => `- ${m.name}: ${m.dosage}`).join('\n');
        } else {
            mText = "No active medications.";
        }

        return { overview: tText, meds: mText };
    };

    const autoData = getAutoGeneratedSummary();

    // Use saved draft OR auto-generated data
    const currentOverview = patient.discharge?.overview || autoData.overview;
    const currentMeds = patient.discharge?.meds || autoData.meds;
    const currentLifestyle = patient.discharge?.lifestyle || '';

    const detailView = `
        <div class="patient-detail-view" style="animation: fadeIn 0.3s ease;">
            <div style="margin-bottom: 2rem; display: flex; align-items: center; justify-content: space-between;">
                <button class="btn" style="border: 1px solid var(--border-color); background: white;" onclick="location.reload()">
                    <i data-lucide="arrow-left"></i> Back to List
                </button>
                <div style="text-align: right;">
                     <h2 style="font-size: 1.5rem; font-weight: 700;">${patient.name}</h2>
                     <p style="color: var(--text-muted);">ID: #${patient.id} | ${patient.age} Yrs | ${patient.gender}</p>
                     <small style="font-size:0.7rem; color: #ccc;">Role: ${currentUser.role} (StaffMode: ${isStaff})</small>
                </div>
            </div>

            <div style="display: grid; grid-template-columns: ${isStaff ? '1fr 2fr' : '2fr 1fr'}; gap: 2rem;">
                
                <!-- Main History Feed (Hidden for Staff) -->
                ${historySection}

                <!-- Side Panel: Treatments & Meds -->
                <div style="display: flex; flex-direction: column; gap: 1.5rem;">
                    
                    <!-- Treatments -->
                    <div class="card">
                        <h4 style="font-weight: 600; margin-bottom: 1rem;">Active Treatments</h4>
                        <div style="display: flex; flex-direction: column; gap: 0.8rem; margin-bottom: 1rem;">
                            ${patient.treatments.map(t => `
                                <div style="padding: 0.8rem; background: var(--bg-body); border-radius: 8px;">
                                    <div style="font-weight: 600; font-size: 0.9rem;">${t.name}</div>
                                    <div style="font-size: 0.8rem; color: var(--text-muted);">${t.duration}</div>
                                </div>
                            `).join('')}
                        </div>
                        ${!isStaff ? `
                        <form onsubmit="handleAddRecord(event, 'treatment', ${id})">
                            <input name="treatment-name" placeholder="Treatment Name" required style="width: 100%; margin-bottom: 0.5rem; padding: 0.5rem; border: 1px solid var(--border-color); border-radius: var(--radius-md);">
                            <input name="treatment-duration" placeholder="Duration (e.g. 7 days)" required style="width: 100%; margin-bottom: 0.5rem; padding: 0.5rem; border: 1px solid var(--border-color); border-radius: var(--radius-md);">
                            <button type="submit" class="btn" style="width: 100%; font-size: 0.8rem; border: 1px solid var(--border-color); background: white;">+ Add Treatment</button>
                        </form>
                        ` : ''}
                    </div>

                    <!-- Medications -->
                    <div class="card">
                        <h4 style="font-weight: 600; margin-bottom: 1rem;">Medications</h4>
                         <div style="display: flex; flex-direction: column; gap: 0.8rem; margin-bottom: 1rem;">
                            ${patient.medications.map(m => `
                                <div style="padding: 0.8rem; background: #F0FDFA; border-radius: 8px; border: 1px solid #CCFBF1;">
                                    <div style="font-weight: 600; font-size: 0.9rem; color: #0F766E;">${m.name}</div>
                                    <div style="font-size: 0.8rem; color: #115E59;">${m.dosage}</div>
                                </div>
                            `).join('')}
                        </div>
                        ${!isStaff ? `
                         <form onsubmit="handleAddRecord(event, 'medication', ${id})">
                            <input name="med-name" placeholder="Medicine Name" required style="width: 100%; margin-bottom: 0.5rem; padding: 0.5rem; border: 1px solid var(--border-color); border-radius: var(--radius-md);">
                            <input name="med-dosage" placeholder="Dosage" required style="width: 100%; margin-bottom: 0.5rem; padding: 0.5rem; border: 1px solid var(--border-color); border-radius: var(--radius-md);">
                            <button type="submit" class="btn" style="width: 100%; font-size: 0.8rem; border: 1px solid var(--border-color); background: white;">+ Add Medicine</button>
                        </form>
                        ` : ''}
                    </div>

                    <!-- Discharge Planning (Manager/Doctor Only) -->
                    ${!isStaff ? `
                    <div class="card" style="border: 1px solid #C7D2FE; background: #EEF2FF;">
                        <h4 style="font-weight: 600; margin-bottom: 1rem; color: #3730A3; display:flex; align-items:center; gap:0.5rem;">
                            <i data-lucide="file-text" width="18"></i> Discharge Planning
                        </h4>
                        
                        <div style="margin-bottom: 1rem; display:flex; justify-content:space-between; align-items:center;">
                            <div style="flex:1; margin-right:10px;">
                                <label style="display:block; font-size:0.75rem; font-weight:600; margin-bottom:0.2rem;">Load Template</label>
                                <select onchange="applyDischargeTemplate(this.value)" style="width:100%; padding:0.4rem; border-radius:4px; border:1px solid #ccc; font-size:0.85rem;">
                                    <option value="">Select...</option>
                                    ${store.getTreatmentTemplates().map(t => `<option value="${t.id}">${t.name}</option>`).join('')}
                                </select>
                            </div>
                            <button onclick="resetDischargeToActuals(${id})" title="Reset to Actual Records" style="margin-top:14px; background:white; border:1px solid #999; border-radius:4px; padding:0.4rem; cursor:pointer;">
                                <i data-lucide="refresh-cw" width="14"></i>
                            </button>
                        </div>
                        
                        <form onsubmit="saveDischargePlan(event, ${id})">
                             <div style="margin-bottom: 0.8rem;">
                                <label style="display:block; font-size:0.8rem; font-weight:600;">Treatment Overview</label>
                                <textarea id="d-overview" name="overview" rows="4" style="width:100%; padding:0.5rem; border:1px solid #ccc; border-radius:4px;">${currentOverview}</textarea>
                                <small style="color:#666; font-size:0.7rem;">Auto-populated from Treatment History. You can edit this.</small>
                            </div>
                            <div style="margin-bottom: 0.8rem;">
                                <label style="display:block; font-size:0.8rem; font-weight:600;">Lifestyle Advice</label>
                                <textarea id="d-lifestyle" name="lifestyle" rows="2" style="width:100%; padding:0.5rem; border:1px solid #ccc; border-radius:4px;">${currentLifestyle}</textarea>
                            </div>
                            <div style="margin-bottom: 1rem;">
                                <label style="display:block; font-size:0.8rem; font-weight:600;">Medicine Continuation</label>
                                <textarea id="d-meds" name="meds" rows="3" style="width:100%; padding:0.5rem; border:1px solid #ccc; border-radius:4px;">${currentMeds}</textarea>
                                <small style="color:#666; font-size:0.7rem;">Auto-populated from Active Meds.</small>
                            </div>
                            
                            <div style="display: flex; gap: 0.5rem;">
                                <button type="submit" class="btn btn-primary" style="flex:1; font-size:0.85rem;">Save Draft</button>
                                <button type="button" onclick="generateDischargeReport(${id})" class="btn" style="flex:1; background:white; border:1px solid #3730A3; color:#3730A3; font-size:0.85rem;">
                                    <i data-lucide="printer" width="14"></i> Print Report
                                </button>
                            </div>
                        </form>
                    </div>
                    ` : ''}

                </div>
            </div>
        </div>
    `;

    document.getElementById('view-container').innerHTML = detailView;
    if (window.lucide) window.lucide.createIcons();
}

window.resetDischargeToActuals = (id) => {
    if (!confirm('This will wipe your current draft and reload from the patient records. Continue?')) return;

    // Clear saved draft
    store.updateDischargeSummary(id, { overview: null, meds: null, lifestyle: null });
    // Reload UI
    renderPatientDetails(id);
};

window.applyDischargeTemplate = (tmplId) => {
    if (!tmplId) return;
    const tmpl = store.getTreatmentTemplates().find(t => t.id === tmplId);
    if (tmpl) {
        document.getElementById('d-overview').value = tmpl.overview;
        document.getElementById('d-lifestyle').value = tmpl.lifestyle;
        document.getElementById('d-meds').value = tmpl.meds;
    }
};

window.saveDischargePlan = (e, id) => {
    e.preventDefault();
    const form = e.target;
    store.updateDischargeSummary(id, {
        overview: form.elements['overview'].value,
        lifestyle: form.elements['lifestyle'].value,
        meds: form.elements['meds'].value
    });
    alert('Discharge Plan Saved!');
};

window.generateDischargeReport = (id) => {
    const p = store.getPatient(id);
    const discharge = p.discharge || {};

    // Create a printable window
    const win = window.open('', '_blank');
    win.document.write(`
        <html>
        <head>
            <title>Discharge Summary - ${p.name}</title>
            <style>
                body { font-family: 'Segoe UI', sans-serif; padding: 40px; color: #333; }
                h1 { border-bottom: 2px solid #2F855A; padding-bottom: 10px; color: #2F855A; }
                .section { margin-bottom: 25px; }
                .label { font-weight: bold; margin-bottom: 5px; color: #555; }
                .content { background: #f9f9f9; padding: 10px; border-left: 4px solid #2F855A; }
                .meta { margin-bottom: 30px; font-size: 0.9em; color: #666; }
                .footer { margin-top: 50px; text-align: center; font-size: 0.8em; color: #999; border-top: 1px solid #eee; padding-top: 20px;}
                @media print { .no-print { display: none; } }
            </style>
        </head>
        <body>
            <div style="text-align:center; margin-bottom:30px;">
                <h2 style="margin:0; color: #2F855A;">Sreedhari Ayurvedic Centre</h2>
                <p style="margin:5px;">Excellence in Traditional Healing</p>
            </div>
            
            <h1>Discharge Summary Report</h1>
            
            <div class="meta">
                <strong>Patient:</strong> ${p.name} (ID: ${p.id})<br>
                <strong>Age/Gender:</strong> ${p.age} / ${p.gender}<br>
                <strong>Date:</strong> ${new Date().toLocaleDateString()}
            </div>
            
            <div class="section">
                <div class="label">Initial Condition</div>
                <div class="content">${p.condition}</div>
            </div>

            <div class="section">
                <div class="label">Treatment Overview</div>
                <div class="content">${discharge.overview || 'N/A'}</div>
            </div>

             <div class="section">
                <div class="label">Lifestyle Usage & Advice</div>
                <div class="content">${discharge.lifestyle || 'N/A'}</div>
            </div>

             <div class="section">
                <div class="label">Medication for Continuation</div>
                <div class="content">${discharge.meds || 'N/A'}</div>
            </div>

            <div class="action-bar no-print" style="margin-top: 40px; text-align: center;">
                <button onclick="window.print()" style="padding: 10px 20px; font-size: 16px; cursor: pointer; background: #2F855A; color: white; border: none; border-radius: 4px;">Print Report</button>
                <button onclick="alert('Email sent to patient!')" style="padding: 10px 20px; font-size: 16px; cursor: pointer; background: #3182CE; color: white; border: none; border-radius: 4px; margin-left: 10px;">Send Email</button>
            </div>

            <div class="footer">
                Generated by Sreedhari Operations Management System<br>
                This is a computer generated document.
            </div>
        </body>
        </html>
    `);
    win.document.close();
};

// Show Add Patient Form
window.showAddPatientForm = () => {
    const formView = `
        <div class="add-patient-view" style="animation: fadeIn 0.3s ease;">
             <div style="margin-bottom: 2rem; display: flex; align-items: center; justify-content: space-between;">
                <button class="btn" style="border: 1px solid var(--border-color); background: white;" onclick="location.reload()">
                    <i data-lucide="arrow-left"></i> Cancel
                </button>
                <h2 style="font-size: 1.5rem; font-weight: 700;">Register New Patient</h2>
            </div>
            
            <div class="card" style="max-width: 800px; margin: 0 auto;">
                <form onsubmit="handleNewPatientSubmit(event)">
                    <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 1.5rem; margin-bottom: 1.5rem;">
                        <div style="position: relative;">
                            <label style="display: block; margin-bottom: 0.5rem; font-weight: 500;">Patient Name *</label>
                            <input name="name" id="new-patient-name" type="text" autocomplete="off" required placeholder="Full Name" oninput="handleNameSearch(this)" style="width: 100%; padding: 0.75rem; border: 1px solid var(--border-color); border-radius: var(--radius-md);">
                            
                            <!-- Autocomplete Dropdown -->
                            <div id="name-search-results" style="display: none; position: absolute; top: 100%; left: 0; right: 0; background: white; border: 1px solid var(--border-color); border-radius: 0 0 8px 8px; box-shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1); z-index: 10; max-height: 200px; overflow-y: auto;"></div>
                        </div>
                        <div>
                            <label style="display: block; margin-bottom: 0.5rem; font-weight: 500;">Contact Number *</label>
                            <input name="contact" id="new-patient-contact" type="tel" required placeholder="Mobile Number" style="width: 100%; padding: 0.75rem; border: 1px solid var(--border-color); border-radius: var(--radius-md);">
                        </div>
                    </div>

                    <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 1.5rem; margin-bottom: 1.5rem;">
                        <div>
                            <label style="display: block; margin-bottom: 0.5rem; font-weight: 500;">Age *</label>
                            <input name="age" type="number" required placeholder="Age" style="width: 100%; padding: 0.75rem; border: 1px solid var(--border-color); border-radius: var(--radius-md);">
                        </div>
                        <div>
                            <label style="display: block; margin-bottom: 0.5rem; font-weight: 500;">Gender *</label>
                            <select name="gender" required style="width: 100%; padding: 0.75rem; border: 1px solid var(--border-color); border-radius: var(--radius-md); background: white;">
                                <option value="">Select...</option>
                                <option value="Male">Male</option>
                                <option value="Female">Female</option>
                                <option value="Other">Other</option>
                            </select>
                        </div>
                        <div>
                            <label style="display: block; margin-bottom: 0.5rem; font-weight: 500;">Status</label>
                            <select name="status" style="width: 100%; padding: 0.75rem; border: 1px solid var(--border-color); border-radius: var(--radius-md); background: white;">
                                <option value="Active">Active (In-Patient)</option>
                                <option value="Out-Patient">Out-Patient</option>
                            </select>
                        </div>
                    </div>

                    <div style="margin-bottom: 2rem;">
                        <label style="display: block; margin-bottom: 0.5rem; font-weight: 500;">Primary Condition / Diagnosis</label>
                        <textarea name="condition" rows="3" placeholder="e.g. Arthritis, Post-stroke care..." style="width: 100%; padding: 0.75rem; border: 1px solid var(--border-color); border-radius: var(--radius-md);"></textarea>
                    </div>
                    
                    <div style="padding-top: 1.5rem; border-top: 1px solid var(--border-color); display: flex; justify-content: flex-end; gap: 1rem;">
                         <button type="button" class="btn" style="border: 1px solid var(--border-color); background: white;" onclick="location.reload()">Cancel</button>
                         <button type="submit" class="btn btn-primary" style="padding: 0.75rem 2rem;">Register Patient</button>
                    </div>
                </form>
            </div>
        </div>
    `;
    document.getElementById('view-container').innerHTML = formView;
    if (window.lucide) window.lucide.createIcons();
};

window.handleNameSearch = (input) => {
    const val = input.value.toLowerCase();
    const resultBox = document.getElementById('name-search-results');

    if (val.length < 2) {
        resultBox.style.display = 'none';
        return;
    }

    const inquiries = store.getInquiries();
    // Filter inquiries that match and aren't fully completely processed yet (optional logic)
    const matches = inquiries.filter(i => i.name.toLowerCase().includes(val));

    if (matches.length > 0) {
        resultBox.innerHTML = matches.map(m => `
            <div onclick="selectPatientFromSearch('${m.name}', '${m.contact}')" style="padding: 0.8rem; cursor: pointer; border-bottom: 1px solid #f0f0f0; transition: background 0.1s;" onmouseover="this.style.background='#f9fafb'" onmouseout="this.style.background='white'">
                <div style="font-weight: 500;">${m.name}</div>
                <div style="font-size: 0.8rem; color: var(--text-muted);">${m.contact} • ${m.type} Inquiry</div>
            </div>
        `).join('');
        resultBox.style.display = 'block';
    } else {
        resultBox.style.display = 'none';
    }
};

window.selectPatientFromSearch = (name, contact) => {
    document.getElementById('new-patient-name').value = name;
    document.getElementById('new-patient-contact').value = contact;
    document.getElementById('name-search-results').style.display = 'none';
};

window.handleNewPatientSubmit = (e) => {
    e.preventDefault();
    const form = e.target;
    const data = {
        name: form.elements['name'].value,
        age: form.elements['age'].value,
        gender: form.elements['gender'].value,
        contact: form.elements['contact'].value,
        condition: form.elements['condition'].value || 'Under Eval',
        status: form.elements['status'].value,
        lastVisit: new Date().toISOString().split('T')[0]
    };

    store.addPatient(data);
    alert('Patient Registered Successfully!');
    // Reload main list
    location.reload();
};

window.viewPatient = (id) => {
    renderPatientDetails(id);
};

export function renderPatients() {
    const patients = store.getPatients(); // Guaranteed to be an array now
    const currentUser = store.getCurrentUser();
    const isStaff = currentUser && currentUser.role === 'Staff';

    return `
        <div class="patients-page">
            <div class="card">
                <div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 2rem;">
                     <div>
                        <h3 style="font-weight: 600; font-size: 1.2rem;">Patient Registry</h3>
                        <p style="color: var(--text-muted); font-size: 0.9rem;">Manage health records and history</p>
                    </div>
                    ${!isStaff ? `
                    <button class="btn btn-primary" onclick="showAddPatientForm()">
                        <i data-lucide="plus" style="vertical-align: middle; margin-right: 4px;"></i> Add New Patient
                    </button>
                    ` : ''}
                </div>

                <div class="table-container">
                    <table>
                        <thead>
                            <tr>
                                <th>Name / ID</th>
                                <th>Age</th>
                                ${!isStaff ? '<th>Condition</th>' : ''}
                                <th>Status</th>
                                <th>Last Visit</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            ${patients.map(p => `
                                <tr>
                                    <td>
                                        <div style="font-weight: 500;">${p.name}</div>
                                        <div style="font-size: 0.8rem; color: var(--text-muted);">#ID-${p.id}</div>
                                    </td>
                                    <td>${p.age}</td>
                                    ${!isStaff ? `<td>${p.condition}</td>` : ''}
                                    <td>
                                        <span class="status-badge ${p.status === 'Active' ? 'bg-green' : 'bg-blue'}">${p.status}</span>
                                    </td>
                                    <td>${p.lastVisit}</td>
                                    <td>
                                        <button class="icon-btn" onclick="viewPatient(${p.id})" title="View Records" style="width: 32px; height: 32px; border: none; background: transparent; cursor: pointer;">
                                            <i data-lucide="eye" style="width: 16px; height: 16px; color: var(--primary);"></i>
                                        </button>
                                    </td>
                                </tr>
                            `).join('')}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    `;
}
